[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm run typecheck:libs",
  "pnpm --filter @workspace/api-server run build",
  "pnpm --filter @workspace/db push"
]

[start]
cmd = "node artifacts/api-server/dist/index.mjs"
